### ISSUE TITLE
Provide sample data

### ISSUE THREAD

**Issue by kephale** [cellcanvas/surforama#12]
We should provide sample data!

@LorenzLamm @rdrighetto do ya'll have some thoughts about what we can provide? Maybe some nice thylakoids and some curved surfaces? 

We could provide it two ways: 
- napari sample data plugin
- expose it on the CLI that @kevinyamauchi just added

Both would use pooch for the download (and ideally the same code path).

**Comment by kevinyamauchi** [comment]
Yes, definitely! On Friday, @lorenzlamm uploaded some demo data to the hackathon google drive folder. I will try to get it on zenodo this week so that we can make a sample data plugin/loader.

Regarding the CLI, I was thinking a `surforama --demo` flag would be a nice route. As you said, it would just call the sample data loader function behind the scenes.

**Comment by LorenzLamm** [comment]
Yes, in our shared GDrive folder, the sample thylakoid membranes are in the ./membranorama/showcase folder.

They are from the previous [thylakoid paper](https://elifesciences.org/articles/53740), where also original Membranorama was introduced.

I also realized that the Covid tomogram we were playing with is already on the [data portal](https://cryoetdataportal.czscience.com/runs/467?prev=%2Fdatasets%2F10006%3Fprev%3D%252Fbrowse-data%252Fdatasets), so we could also us this?

**Comment by kevinyamauchi** [comment]
We can have both!

**Comment by rdrighetto** [comment]
I can put together some sample data on Zenodo this week. These two should be fine (thylakoids and covid). What files are needed exactly? Just the tomogram and the mesh in .obj format?

**Comment by kevinyamauchi** [comment]
@rdrighetto I added the thylakoid example just now (#18). If you'd like to contribute a covid example, that would be awesome! We just need the tomogram (mrc file) and corresponding mesh (obj file) on zenodo.

**Comment by kevinyamauchi** [comment]
If you'd like to checkout the new demo, you can run `surforama --demo` from main!
