### ISSUE TITLE
add napari as an optional dependency

### ISSUE THREAD

**Issue by kevinyamauchi** [cellcanvas/surforama#15]
We should consider adding napari as an optional dependency so that people can install everything with one command.

Suggested by @rdrighetto in zulip: https://imagesc.zulipchat.com/#narrow/stream/427861-Biozentrum-Napari-MemBrain-Hackathon-2024/topic/surforama/near/426113294

**Comment by kevinyamauchi** [comment]
Should we mirror the napari API? That is, one could use `pip install surforama[all]` to install surforama + napari + PyQt5?

**Comment by rdrighetto** [comment]
Yes, that's what I had in mind :-)

**Comment by kevinyamauchi** [comment]
I added a `pip install surforama[napari]` option in #25
