### ISSUE TITLE
Color the mesh upon "start surfing"

### ISSUE THREAD

**Issue by rdrighetto** [cellcanvas/surforama#43]
A minor glitch at the moment is that upon opening a tomogram and a mesh, the mesh is not colored immediately by the tomogram data. This first occurs when one of the sliders (Extend/contrast surface or Surface Thickness) are changed.

Can we make the mesh become colored upon clicking the "start surfing" button instead?

**Comment by kevinyamauchi** [comment]
Thanks for making this issue, @rdrighetto ! This has been bothering me too. We should definitely fix this.

**Comment by rdrighetto** [comment]
I have tried a few things in the code but without success so far. Thought would be easy 😅

**Comment by kevinyamauchi** [comment]
Ah yeah, it looks like the code to set the colors on the mesh is a bit spread out. I took a quick look and put some notes below.

This is where the colors are initially set when you click "start surfing":
https://github.com/cellcanvas/surforama/blob/210dc2169563bb3677a3f768f1500ad99b9ce49a/src/surforama/app.py#L168-L174

We would need to replace `self.color_values =` (line 168) with the intensity values of the image at the mesh vertices.

This is how colors are updated when the expand/contract slider is used:
https://github.com/cellcanvas/surforama/blob/210dc2169563bb3677a3f768f1500ad99b9ce49a/src/surforama/app.py#L241-L251

- `self.get_point_colors()` is called to get the intensity values
- The colors are assigned to `self.color_values` (line 249)
- the mesh is updated on line 251

Based on this, I think we could use `self.get_point_colors()` to set the colors on line 168. I believe you would pass the mesh vertices as the input argument.

In the long run, I think we need to refactor a bit to consolidate and unify the mesh coloring code, but this might be a good fix for now.

**Comment by kevinyamauchi** [comment]
Want to give it a go, @rdrighetto ?

**Comment by rdrighetto** [comment]
Hey @kevinyamauchi, sorry for the delay! I looked into this with @LorenzLamm here in Munich and we believe it is now solved, please see the PR 🙂

**Comment by kevinyamauchi** [comment]
No stress. Thanks for the PR @rdrighetto and @LorenzLamm ! I just merged it and will cut a release now.
